//go:build ignore

// gen reads the shared UCUM unit list and writes atoms_gen.go. Run it with `go generate ./...`.
package main

import (
	"bytes"
	"encoding/xml"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

const source = "../../../../domains/weather/standards/ucum/ucum-essence.xml"

type entry struct {
	XMLName  xml.Name
	Code     string `xml:"Code,attr"`
	IsMetric string `xml:"isMetric,attr"`
}

type root struct {
	Entries []entry `xml:",any"`
}

func main() {
	f, err := os.Open(source)
	if err != nil {
		fail(err)
	}
	defer f.Close()

	dec := xml.NewDecoder(f)
	// The file declares encoding="ascii", which encoding/xml does not know. ASCII is valid UTF-8.
	dec.CharsetReader = func(_ string, in io.Reader) (io.Reader, error) { return in, nil }

	var doc root
	if err := dec.Decode(&doc); err != nil {
		fail(err)
	}

	atoms := map[string]bool{} // code -> takes a metric prefix
	var prefixes []string
	for _, e := range doc.Entries {
		switch e.XMLName.Local {
		case "prefix":
			prefixes = append(prefixes, e.Code)
		case "base-unit":
			atoms[e.Code] = true // SI base units all take prefixes
		case "unit":
			atoms[e.Code] = e.IsMetric == "yes"
		}
	}
	sort.Strings(prefixes)

	codes := make([]string, 0, len(atoms))
	for c := range atoms {
		codes = append(codes, c)
	}
	sort.Strings(codes)

	var b bytes.Buffer
	b.WriteString("// Code generated by gen.go from the UCUM unit list; DO NOT EDIT.\n\npackage ucum\n\n")
	b.WriteString("// atoms maps every UCUM atom code to whether it takes a metric prefix.\nvar atoms = map[string]bool{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\t%q: %t,\n", c, atoms[c])
	}
	b.WriteString("}\n\n// prefixes are the UCUM metric prefix codes.\nvar prefixes = []string{" + quoteAll(prefixes) + "}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("atoms_gen.go", out, 0o644); err != nil {
		fail(err)
	}
}

func quoteAll(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(q, ", ")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
