"""Build contracts/wcag-catalog.openapi.yaml from the W3C wcag.json files in standards/wcag."""
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "standards" / "wcag"
out = root / "contracts" / "wcag-catalog.openapi.yaml"

d22 = json.loads((src / "wcag-2.2.json").read_text(encoding="utf8"))
d21 = json.loads((src / "wcag-2.1.json").read_text(encoding="utf8"))

def criteria(d):
    for p in d["principles"]:
        for g in p["guidelines"]:
            for sc in g["successcriteria"]:
                yield p["handle"], g["num"], sc

# union across versions so 2.0/2.1-only criteria (e.g. 4.1.1) stay addressable
seen = {}
for d in (d21, d22):
    for principle, gnum, sc in criteria(d):
        seen[sc["num"]] = dict(num=sc["num"], handle=sc["handle"], level=sc["level"],
                               versions=sc["versions"], principle=principle, guideline=gnum)
rows = sorted(seen.values(), key=lambda r: [int(x) for x in r["num"].split(".")])

lines = [
    "# GENERATED by scripts/build_wcag_catalog.py from standards/wcag/wcag-2.1.json and wcag-2.2.json.",
    "# Do not edit by hand.",
    "openapi: 3.1.0",
    "info:",
    "  title: WCAG 2.x Success Criteria Catalog",
    "  version: 0.1.0",
    "  description: Success criterion identifiers, levels, and versions, taken directly from W3C data.",
    "paths: {}",
    "components:",
    "  schemas:",
    "    WcagSuccessCriterionId:",
    "      type: string",
    "      description: WCAG success criterion number, e.g. 1.4.3.",
    "      enum:",
]
lines += [f'        - "{r["num"]}"' for r in rows]
lines += [
    "    WcagSuccessCriterion:",
    "      type: object",
    "      required: [id, name, level, versions]",
    "      properties:",
    "        id: { $ref: '#/components/schemas/WcagSuccessCriterionId' }",
    "        name: { type: string }",
    "        level: { type: string, enum: [A, AA, AAA] }",
    "        versions:",
    "          type: array",
    "          items: { type: string, enum: ['2.0', '2.1', '2.2'] }",
    "    WcagCatalog:",
    "      type: array",
    "      items: { $ref: '#/components/schemas/WcagSuccessCriterion' }",
    "      examples:",
    "        -",
]
for r in rows:
    name = r["handle"].replace('"', '\\"')
    v = ", ".join(f"'{x}'" for x in r["versions"])
    lines.append(f'          - {{ id: "{r["num"]}", name: "{name}", level: {r["level"]}, versions: [{v}] }}')
out.write_text("\n".join(lines) + "\n", encoding="utf8")
print(len(rows), "criteria ->", out)
