// Reads the shared UCUM unit list and writes src/ucum/atoms.gen.ts.
//   npm run gen:ucum          regenerate the file
//   npm run check:ucum        fail if the checked-in file is out of date
// Node built-ins only. The XML is regular enough (one element per tag, attributes in
// double quotes) that a tag scan is sufficient, and it keeps the toolchain dependency-free.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const source = resolve(import.meta.dirname, '../../../../domains/weather/standards/ucum/ucum-essence.xml');
const target = resolve(import.meta.dirname, '../src/ucum/atoms.gen.ts');

// The file declares encoding="ascii". Node has no such decoder name, but ASCII is a subset
// of Latin-1, so reading it as latin1 is lossless.
const xml = readFileSync(source, 'latin1');

const entities = { quot: '"', apos: "'", amp: '&', lt: '<', gt: '>' };
function decode(text) {
  return text.replace(/&(#x[0-9a-fA-F]+|#[0-9]+|[a-z]+);/g, (whole, body) => {
    if (body.startsWith('#x')) return String.fromCodePoint(parseInt(body.slice(2), 16));
    if (body.startsWith('#')) return String.fromCodePoint(parseInt(body.slice(1), 10));
    return Object.hasOwn(entities, body) ? entities[body] : whole;
  });
}

function attribute(tag, name) {
  // Leading whitespace keeps `Code` from matching the case-insensitive `CODE` attribute.
  const m = new RegExp(`\\s${name}="([^"]*)"`).exec(tag);
  return m ? decode(m[1]) : undefined;
}

const version = /<root\b[^>]*\sversion="([^"]*)"/.exec(xml)?.[1] ?? 'unknown';
const atoms = new Map(); // code -> takes a metric prefix
const prefixes = [];
for (const m of xml.matchAll(/<(prefix|base-unit|unit)\s[^>]*>/g)) {
  const [tag, kind] = m;
  const code = attribute(tag, 'Code');
  if (code === undefined) throw new Error(`no Code attribute in ${tag}`);
  if (kind === 'prefix') prefixes.push(code);
  else if (kind === 'base-unit') atoms.set(code, true); // SI base units all take prefixes
  else atoms.set(code, attribute(tag, 'isMetric') === 'yes');
}
if (atoms.size < 300 || prefixes.length < 20) {
  throw new Error(`suspiciously small unit list: ${atoms.size} atoms, ${prefixes.length} prefixes`);
}

const byCodeUnit = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
prefixes.sort(byCodeUnit);
const codes = [...atoms.keys()].sort(byCodeUnit);

const lines = [
  '// Code generated by scripts/gen-ucum.mjs from the UCUM unit list; DO NOT EDIT.',
  `// Source: domains/weather/standards/ucum/ucum-essence.xml, UCUM version ${version}.`,
  '',
  '/**',
  ' * Every UCUM atom code, mapped to whether it takes a metric prefix. A Map rather than an object',
  ' * literal, so a lookup of "constructor" or "__proto__" cannot find an inherited member.',
  ' */',
  'export const atoms: ReadonlyMap<string, boolean> = new Map<string, boolean>([',
  ...codes.map((c) => `  [${JSON.stringify(c)}, ${atoms.get(c)}],`),
  ']);',
  '',
  '/** The UCUM metric prefix codes. */',
  `export const prefixes: readonly string[] = [${prefixes.map((p) => JSON.stringify(p)).join(', ')}];`,
  '',
];
const output = lines.join('\n');

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(target, 'utf8');
  } catch {}
  if (current !== output) {
    console.error('src/ucum/atoms.gen.ts is out of date. Run `npm run gen:ucum`.');
    process.exit(1);
  }
  console.log(`atoms.gen.ts is current (${atoms.size} atoms, ${prefixes.length} prefixes).`);
} else {
  writeFileSync(target, output, 'utf8');
  console.log(`wrote ${target}: ${atoms.size} atoms, ${prefixes.length} prefixes.`);
}
