//! Reads the shared UCUM unit list and writes `src/ucum/atoms_gen.rs`.
//!
//! Run it with `cargo run --example gen_ucum` from the crate root. The generated file is
//! checked in, so a normal build and `cargo test` need no generation step.
//!
//! The XML is machine-written with one element start tag per unit or prefix, so a scan of
//! the start tags is enough and no XML crate is needed. The file declares `encoding="ascii"`,
//! which is valid UTF-8, so it is read as a `String`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

const SOURCE: &str = "../../../domains/weather/standards/ucum/ucum-essence.xml";
const TARGET: &str = "src/ucum/atoms_gen.rs";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(message) => {
            eprintln!("gen_ucum: {message}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let xml =
        fs::read_to_string(root.join(SOURCE)).map_err(|e| format!("reading {SOURCE}: {e}"))?;

    let mut atoms: BTreeMap<String, bool> = BTreeMap::new(); // code -> takes a metric prefix
    let mut prefixes: Vec<String> = Vec::new();

    let mut rest = xml.as_str();
    while let Some(start) = rest.find('<') {
        rest = &rest[start + 1..];
        let end = rest.find('>').ok_or("unterminated tag")?;
        let tag = &rest[..end];
        rest = &rest[end + 1..];

        let name = tag.split_whitespace().next().unwrap_or("");
        if !matches!(name, "prefix" | "base-unit" | "unit") {
            continue;
        }
        let code = attribute(tag, "Code").ok_or_else(|| format!("<{name}> without Code: {tag}"))?;
        if code.contains('&') {
            return Err(format!("entity in code {code:?} is not handled"));
        }
        match name {
            "prefix" => prefixes.push(code),
            // SI base units all take prefixes.
            "base-unit" => {
                atoms.insert(code, true);
            }
            _ => {
                let metric = attribute(tag, "isMetric").as_deref() == Some("yes");
                atoms.insert(code, metric);
            }
        }
    }
    prefixes.sort();

    let mut out = String::new();
    out.push_str(
        "// Code generated by examples/gen_ucum.rs from the UCUM unit list; DO NOT EDIT.\n\n",
    );
    out.push_str("/// Every UCUM atom code, sorted, with whether it takes a metric prefix.\n");
    out.push_str("pub(super) static ATOMS: &[(&str, bool)] = &[\n");
    for (code, metric) in &atoms {
        writeln!(out, "    ({code:?}, {metric}),").map_err(|e| e.to_string())?;
    }
    out.push_str("];\n\n/// The UCUM metric prefix codes, sorted.\n");
    out.push_str("pub(super) static PREFIXES: &[&str] = &[\n");
    for prefix in &prefixes {
        writeln!(out, "    {prefix:?},").map_err(|e| e.to_string())?;
    }
    out.push_str("];\n");

    fs::write(root.join(TARGET), out).map_err(|e| format!("writing {TARGET}: {e}"))?;
    println!(
        "wrote {} atoms and {} prefixes to {TARGET}",
        atoms.len(),
        prefixes.len()
    );
    Ok(())
}

/// Returns the value of `name="..."` in a start tag. The match is case-sensitive, so
/// `Code` does not match `CODE`.
fn attribute(tag: &str, name: &str) -> Option<String> {
    let needle = format!(" {name}=\"");
    let from = tag.find(&needle)? + needle.len();
    let len = tag[from..].find('"')?;
    Some(tag[from..from + len].to_string())
}
